#!/usr/bin/env php
<?php

/**
 * @author Alireza Josheghani <josheghani.dev@gmail.com>
 * @version 1.1
 * @package Lemax Console Component v1.1
 */

use Josh\Console;

if(file_exists(__DIR__.'/../../vendor/autoload.php')):
    require __DIR__.'/../../vendor/autoload.php';
else:
    require __DIR__.'/vendor/autoload.php';
endif;

$console = new Console;
$console->start();
